### ISSUE TITLE
Repeated items in playlist "My favorites"

### ISSUE THREAD

**Issue by immartian** [Musicoin/client-reworked#1]
After tipping the same song several times, they were all going to "My favorite" playlist, but displaying as several items instead of same song. 
![image](https://cloud.githubusercontent.com/assets/81030/20031483/1356e080-a3b3-11e6-999a-060b4fc83c3b.png)

**Comment by phiferd** [comment]
I had made a decision to allow the same song to appear multiple times in a playlist, as I didn't see any reason to prevent the user from doing that if they wanted to.  However, I agreed that the automatic add to "My Favorites" should not add a duplicate.  I will add logic to the tipping case to prevent this.

**Comment by immartian** [comment]
What's the current logic of adding to "My favorites" when I click playlist icon? Will it be tipped before adding into the playlist as a consistency?

**Comment by phiferd** [comment]
Fixed. Duplicate items are allowed in playlists, but tipping will not add an item that is already in My Favorites.
