### ISSUE TITLE
"Tip" button keeps "Failed!" status 

### ISSUE THREAD

**Issue by immartian** [Musicoin/client-reworked#2]
The tip button met a "failed" message in an occasion(can't repeat it). Nonetheless, the red status keeps showing even switch to other songs and won't change back to green "tip" button in the whole session until restart the app. 

![image](https://cloud.githubusercontent.com/assets/81030/20038977/67b5e2f6-a477-11e6-90fe-ad2614577d86.png)

**Comment by phiferd** [comment]
Fixed in most recent commit: https://github.com/Musicoin/client-reworked/commit/870660384d6f0b70687526d96e207b513b0cefb6
